- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: create VprofileVPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Create Public Subnet 1 in Zone 1
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        map_public: yes
        tags:
          Name: vprofile_pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2 in Zone 2
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub2Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        map_public: yes
        tags:
          Name: vprofile_pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3 in Zone 3
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub3Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        map_public: yes
        tags:
          Name: vprofile_pubsub3
      register: pubsub3_out

    - name: Create Private Subnet 1 in Zone 1
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PrivSub1Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        tags:
          Name: vprofile_privsub1
      register: privsub1_out

    - name: Create Private Subnet 2 in Zone 2
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        cidr: "{{ PrivSub2Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        tags:
          Name: vprofile_privsub2
      register: privsub2_out

    - name: Create Private Subnet 3 in Zone 3
      ec2_vpc_subnet:
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        cidr: "{{ PrivSub3Cidr }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        tags:
          Name: vprofile_privsub3
      register: privsub3_out

    - name: Create Internet Gateway
      ec2_vpc_igw:
        region: "{{ region }}"
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        tags:
          Name: vprofile_IGW
      register: igw_out

    - name: setup public subnet route table
      ec2_vpc_route_table:
        region: "{{ region }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        tags:
          Name: vprofile_PubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pubRT_out

    - name: Create NAT Gateway and allocate new EIP if NAT Gateway does not already exist
      ec2_vpc_nat_gateway:
        state: "{{ state }}"
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        wait: yes
        region: "{{ region }}"
        if_exist_do_not_create: true
        tags:
          Name: vprofile_NATGW
      register: NATGW_out
    - name: Create private subnet route table
      ec2_vpc_route_table:
        region: "{{region}}"
        vpc_id: "{{vpcout.vpc.id}}"
        tags:
          Name: "vprofile_PrivRT"
        subnets:
          - "{{ privsub1_out.subnet.id }}"
          - "{{ privsub2_out.subnet.id }}"
          - "{{ privsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ NATGW_out.nat_gateway_id }}"
      register: PrivRT_out

    - debug:
        var: "{{ item }}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw_out.gateway_id
        - pubRT_out.route_table.id
        - PrivRT_out.route_table.id
        - NATGW_out.nat_gateway_id
    - name: Set facts for VPC output
      set_fact:
        vpcid: "{{ vpcout.vpc.id }}"
        pubsub1id: "{{ pubsub1_out.subnet.id }}"
        pubsub2id: "{{ pubsub2_out.subnet.id }}"
        pubsub3id: "{{ pubsub3_out.subnet.id }}"
        privsub1id: "{{ privsub1_out.subnet.id }}"
        privsub2id: "{{ privsub2_out.subnet.id }}"
        privsub3id: "{{ privsub3_out.subnet.id }}"
        igwid: "{{ igw_out.gateway_id }}"
        pubRTid: "{{ pubRT_out.route_table.id }}"
        privRTid: "{{ PrivRT_out.route_table.id }}"
        NATGWid: "{{ NATGW_out.nat_gateway_id }}"
        cacheable: yes

    - name: Create variables file for vpc module output
      copy:
        content: "{{ vpcid }}\n{{ pubsub1id }}\n{{ pubsub2id }}\n{{ pubsub3id }}\n{{ privsub1id }}\n{{ privsub2id }}\n{{ privsub3id }}\n{{ igwid }}\n{{ pubRTid }}\n{{ privRTid }}\n{{ NATGWid }}\n"
        dest: vars/output_vars
      
